# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserAddresses.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='UserAddresses.proto',
  package='UserAddresses',
  syntax='proto3',
  serialized_pb=_b('\n\x13UserAddresses.proto\x12\rUserAddresses\"\x19\n\x0bUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x80\x01\n\x0cUserResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x36\n\taddresses\x18\x03 \x03(\x0b\x32#.UserAddresses.UserResponse.Address\x1a\x1b\n\x07\x41\x64\x64ress\x12\x10\n\x08location\x18\x01 \x01(\t2P\n\rUserAddresses\x12?\n\x04List\x12\x1a.UserAddresses.UserRequest\x1a\x1b.UserAddresses.UserResponseb\x06proto3')
)




_USERREQUEST = _descriptor.Descriptor(
  name='UserRequest',
  full_name='UserAddresses.UserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='UserAddresses.UserRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=63,
)


_USERRESPONSE_ADDRESS = _descriptor.Descriptor(
  name='Address',
  full_name='UserAddresses.UserResponse.Address',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='location', full_name='UserAddresses.UserResponse.Address.location', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=194,
)

_USERRESPONSE = _descriptor.Descriptor(
  name='UserResponse',
  full_name='UserAddresses.UserResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='UserAddresses.UserResponse.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='email', full_name='UserAddresses.UserResponse.email', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='addresses', full_name='UserAddresses.UserResponse.addresses', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_USERRESPONSE_ADDRESS, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=194,
)

_USERRESPONSE_ADDRESS.containing_type = _USERRESPONSE
_USERRESPONSE.fields_by_name['addresses'].message_type = _USERRESPONSE_ADDRESS
DESCRIPTOR.message_types_by_name['UserRequest'] = _USERREQUEST
DESCRIPTOR.message_types_by_name['UserResponse'] = _USERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserRequest = _reflection.GeneratedProtocolMessageType('UserRequest', (_message.Message,), dict(
  DESCRIPTOR = _USERREQUEST,
  __module__ = 'UserAddresses_pb2'
  # @@protoc_insertion_point(class_scope:UserAddresses.UserRequest)
  ))
_sym_db.RegisterMessage(UserRequest)

UserResponse = _reflection.GeneratedProtocolMessageType('UserResponse', (_message.Message,), dict(

  Address = _reflection.GeneratedProtocolMessageType('Address', (_message.Message,), dict(
    DESCRIPTOR = _USERRESPONSE_ADDRESS,
    __module__ = 'UserAddresses_pb2'
    # @@protoc_insertion_point(class_scope:UserAddresses.UserResponse.Address)
    ))
  ,
  DESCRIPTOR = _USERRESPONSE,
  __module__ = 'UserAddresses_pb2'
  # @@protoc_insertion_point(class_scope:UserAddresses.UserResponse)
  ))
_sym_db.RegisterMessage(UserResponse)
_sym_db.RegisterMessage(UserResponse.Address)



_USERADDRESSES = _descriptor.ServiceDescriptor(
  name='UserAddresses',
  full_name='UserAddresses.UserAddresses',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=196,
  serialized_end=276,
  methods=[
  _descriptor.MethodDescriptor(
    name='List',
    full_name='UserAddresses.UserAddresses.List',
    index=0,
    containing_service=None,
    input_type=_USERREQUEST,
    output_type=_USERRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_USERADDRESSES)

DESCRIPTOR.services_by_name['UserAddresses'] = _USERADDRESSES

# @@protoc_insertion_point(module_scope)
