# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import UserAddresses_pb2 as UserAddresses__pb2


class UserAddressesStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.List = channel.unary_unary(
        '/UserAddresses.UserAddresses/List',
        request_serializer=UserAddresses__pb2.UserRequest.SerializeToString,
        response_deserializer=UserAddresses__pb2.UserResponse.FromString,
        )


class UserAddressesServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def List(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UserAddressesServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'List': grpc.unary_unary_rpc_method_handler(
          servicer.List,
          request_deserializer=UserAddresses__pb2.UserRequest.FromString,
          response_serializer=UserAddresses__pb2.UserResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'UserAddresses.UserAddresses', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
